//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webcvone.Models.entitty
{
    using System;
    using System.Collections.Generic;
    
    public partial class aciklamalar
    {
        public string aciklama_info { get; set; }
        public string aciklama_info1 { get; set; }
        public string aciklama_info2 { get; set; }
        public int ID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
    }
}
