//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webcvone.Models.entitty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_log
    {
        public int ID { get; set; }
        public string Admeyn { get; set; }
        public Nullable<int> Log_keytrue { get; set; }
    }
}
