//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webcvone.Models.entitty
{
    using System;
    using System.Collections.Generic;
    
    public partial class detay_profil
    {
        public int ıd { get; set; }
        public string Sırket { get; set; }
        public string deneyim_notu { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string Pozisyon { get; set; }
    }
}
