//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webcvone.Models.entitty
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webcvrepoEntities : DbContext
    {
        public webcvrepoEntities()
            : base("name=webcvrepoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aciklamalar> aciklamalar { get; set; }
        public virtual DbSet<detay_profil> detay_profil { get; set; }
        public virtual DbSet<Iletisim> Iletisim { get; set; }
        public virtual DbSet<tbl_egitim> tbl_egitim { get; set; }
        public virtual DbSet<tbl_sertifika> tbl_sertifika { get; set; }
        public virtual DbSet<work_flow> work_flow { get; set; }
        public virtual DbSet<Admin_log> Admin_log { get; set; }
    }
}
