//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webcvone.Models.entitty
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_egitim
    {
        public int ID { get; set; }
        public string OkulAd { get; set; }
        public string Bolum { get; set; }
        public string EgitimDetay { get; set; }
        public string SertifikaDetay { get; set; }
        public string GPA { get; set; }
        public string MezuniyetYili { get; set; }
    }
}
